default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: politics-api_development

test:
  <<: *default
  database: politics-api_test

production:
  <<: *default
  database: politics-api_production
  username: politics-api
  password: <%= ENV['POLITICS-API_DATABASE_PASSWORD'] %>
